# Generated by Django 3.2 on 2023-01-30 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_alter_lesson_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={"ordering": ("-created",), "verbose_name": "News", "verbose_name_plural": "News"},
        ),
    ]
